config/routes.rb
Rails.application.routes.draw do
  resources :patients
  devise_for :employees
  root "patients#index"
  get "qr/code"
  get "app", to: 'app#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/medical_attachment.rb
class MedicalAttachment < ApplicationRecord
  belongs_to :patient

  has_attached_file :file
  validates_attachment_content_type :file, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]

  def file_url
    file.url(:medium)
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  include PgSearch

  pg_search_scope :search_by_fullname, :against => [:firstname, :lastname]

  has_many :medical_attachments
  accepts_nested_attributes_for :medical_attachments
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
    render layout: false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_employee!, except: [:show]

  # GET /patients
  # GET /patients.json
  def index
    search = params[:search]
    if search.present?
      @patients = Patient.search_by_fullname(search)
    else
      @patients = Patient.order(:firstname, :lastname)
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    respond_to do |format|
      format.html
      format.json{
        render :json => @patient.to_json({:include => {:medical_attachments => {:methods => :file_url}}})
      }
    end
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        if params[:medical_attachments]
          params[:medical_attachments].each do |medical_attachment|
            @patient.medical_attachments.create(file: medical_attachment)
          end
        end
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
          if params[:medical_attachments]
          params[:medical_attachments].each do |medical_attachment|
            @patient.medical_attachments.create(file: medical_attachment)
          end
        end
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :birthday, :email, :publickey)
    end
end

app/controllers/qr_controller.rb
class QrController < ApplicationController
  before_action :authenticate_employee!
  def code
    @qrcode = RQRCode::QRCode.new("#{{ssid:'AltEichenHospital', ip:'192.162.18.23', key:'adsipnqwiprnfipqwnfipq'}.to_json}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
  def has_public_key?(patient)
    patient.publickey.present?
  end
end

app/views/app/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Gesundheitscloud</title>
  <link rel="stylesheet" href="/css/bootstrap.css">
  <link rel="stylesheet" href="/css/bootstrap-theme.css">
  <link rel="stylesheet" href="/css/style.css">
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="#">Gesundheitscloud</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>

  <div class="content">

      <div class="product-preview">
        <div class="row" id="product-preview-row">
        <a href="zxing://scan/?ret=http%3A%2F%2F172.20.10.3%3A3000%2Fapp%2F%3F" class="btn btn-primary">Scan QR Code</a>
        </div>
      </div>

    </div>

    <script src="/js/jquery-3.2.1.min.js" charset="utf-8"></script>
    <script src="/js/bootstrap.js" charset="utf-8"></script>

    <script type="text/javascript">
      // medical_attachments
      if (window.location.href.includes('?')) {
        $.ajax({
          url: '/patients/4.json',
          contentType: 'application/json',
          success: function(response) {

            $('#product-preview-row').html("");
            for (const i in response.medical_attachments) {

              $('#product-preview-row').append(`<div class="col-lg-3 col-md-6 col-xs-6">
                <a class="thumbnail">
                 <img class="thumbnail-img" src="/img/${response.medical_attachments[i].file_file_name.endsWith("jpg") ? "jpg" : "pdf"}.png">

                      <a href="${response.medical_attachments[i].file_url.replace("medium", "original")}"><h4>${response.medical_attachments[i].file_file_name}</h4></a>

                 </a>
              </div>`);
            }
          }
        });
      } else {
        //$('.content').html('');
      }
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GesundheitscloudWeb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">hackhpi</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%if employee_signed_in? %>
          <li><%= link_to 'logout', destroy_employee_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

 <div class="container">

    <%= yield %>
  </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= bootstrap_form_for(patient, html: { multipart: true }) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :firstname, id: :patient_firstname %>
  </div>

  <div class="field">
    <%= form.text_field :lastname, id: :patient_lastname %>
  </div>

  <div class="field">
    <%= form.date_select :birthday, id: :patient_birthday %>
  </div>

  <div class="field">
    <%= form.text_field :email, id: :patient_email %>
  </div>

  <div class="field">
    <%= form.text_area :publickey, id: :patient_publickey %>
  </div>

    <%= file_field_tag "medical_attachments[]", type: :file, multiple: true %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_information.html.erb
<div class="row well">
      <div class="col-6">
        <p>
          <strong>Firstname:</strong>
          <%= patient.firstname %>
        </p>
      </div>

      <div class="col-6">
        <p>
          <strong>Lastname:</strong>
          <%= patient.lastname %>
        </p>
      </div>

      <div class="col-12">
        <p>
          <strong>Birthday:</strong>
          <%= patient.birthday %>
        </p>
      </div>

      <div class="col-12">
        <p>
          <strong>Email:</strong>
          <%= patient.email %>
        </p>
      </div>

      <div class="col-12">
        <p>
          <strong>Publickey:</strong>
          <%= patient.publickey %>
        </p>
      </div>
</div>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="search_controls">
      <form action="/" method="get" class="form-inline">
        <div class="input-group">
          <input type="text" class="form-control" name="search" placeholder="Suche nach Patienten...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Suchen</button>
          </span>
        </div><!-- /input-group -->
      </form>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="row patients-list">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Vorname</th>
          <th>Nachname</th>
          <th>Geburtstag</th>
          <th>Email</th>
          <th>Schlüssel</th>
          <th>Aktionen</th>
        </tr>
      </thead>

      <tbody>
        <% @patients.each_with_index do |patient, index| %>
         <% cache patient do %>
          <tr class="<% if has_public_key?(patient) == false %>no-key<% end %>">
            <th scope="row"><%= index + 1 %></th>
            <td><%= patient.firstname %></td>
            <td><%= patient.lastname %></td>
            <td><%= patient.birthday %></td>
            <td><%= patient.email %></td>
            <td>
              <% if has_public_key?(patient) %>
                Vorhanden
              <% else %>
                  Nein
              <% end %>
            </td>
            <td><%= link_to 'Show', patient %> | <%= link_to 'Edit', edit_patient_path(patient) %> | <%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>


<%= render 'information', patient: @patient %>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/qr/code.html.erb
<div class="qrcode">
  <%= raw @qrcode.as_html %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div>

  <p>
    <strong>Firstname:</strong>
    <%= @user.firstname %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= @user.lastname %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= @user.birthday %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Publickey:</strong>
    <%= @user.publickey %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>